import type { Metadata } from "next";
import { ClerkProvider, } from '@clerk/nextjs'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./layout/Navbar";
import QualificationForm from "./card/QualificationForm";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Horizon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <Navbar/>
    
          </header>
          <div className="relative min-h-screen w-full overflow-x-hidden bg-neutral-950 text-neutral-100 ">
      
             {/*  Subtle Structural Tech Grid */}
             <div className="absolute inset-0 bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-size-[24px_24px] pointer-events-none" />

             {/*  Soft Ambient Blur Effect (Behind Content) */}
             <div className="absolute top-[-10%] left-[-10%] h-125 w-125 rounded-full bg-amber-500/10 blur-[120px] pointer-events-none" />
             <div className="absolute top-[20%] right-[-10%] h-150 w-150 rounded-full bg-indigo-500/5 blur-[150px] pointer-events-none" />

            {/* Page Content */}
            <main className="relative z-10 pt-16">
               {children}
            </main>
          </div>          
        </ClerkProvider>
      </body>
    </html>
  );
}
